(function () {
  'use strict';
  window.IDC = window.IDC || { widgets: {} };

  const ROOT = {
    name: '/', desc: 'The root of the entire filesystem. Every file, directory, and mounted drive lives somewhere under /. There are no drive letters — it is one unified tree.',
    examples: null,
    children: [
      { name: 'bin', desc: 'Essential command binaries available to all users. Contains the fundamental programs needed at boot — before other filesystems are mounted. These commands must always be accessible.', examples: 'ls, cp, mv, cat, chmod, bash, echo, grep' },
      { name: 'boot', desc: 'Files required to start the system: the Linux kernel image, the initial RAM disk (initrd), and bootloader configuration. Do not delete anything here.', examples: 'vmlinuz (kernel image), initrd.img, grub/grub.cfg' },
      { name: 'dev', desc: 'Device files. In Linux, hardware devices are represented as files. Hard drives, terminals, USB ports, and even /dev/null all appear here. Programs interact with hardware by reading and writing these files.', examples: 'sda (first disk), tty (terminal), null, random, zero' },
      { name: 'etc', desc: 'System-wide configuration files — the first place to look when configuring any service. Nearly all Linux configuration is stored as human-readable text files here. Only root can modify most of them.', examples: 'passwd, hosts, fstab, ssh/sshd_config, nginx/nginx.conf, cron.d/' },
      { name: 'home', desc: 'Home directories for regular user accounts. Each user gets a personal subdirectory (/home/alice, /home/bob) for their own files, settings, and configurations. Users have full control over their own home directory.', examples: '/home/alice/, /home/bob/, /home/student/' },
      { name: 'lib', desc: 'Shared libraries required by the essential binaries in /bin and /sbin — the Linux equivalent of Windows .dll files. These libraries must be available at boot before /usr is mounted.', examples: 'libc.so (C standard library), libm.so, libpthread.so' },
      { name: 'media', desc: 'Mount points for removable media that the system attaches automatically. When you plug in a USB drive or insert a disc, it appears as a subdirectory here.', examples: '/media/usb0/, /media/cdrom/' },
      { name: 'mnt', desc: 'A general-purpose staging area for temporarily mounting filesystems manually. Administrators use this when attaching network shares or additional drives for short-term access.', examples: '(typically empty; used temporarily: mount /dev/sdb1 /mnt)' },
      { name: 'opt', desc: 'Optional third-party software that installs outside the standard package manager hierarchy. Large commercial applications often self-contain their files here to avoid conflicts with system packages.', examples: 'google/, zoom/, oracle/' },
      { name: 'proc', desc: 'A virtual filesystem generated by the kernel in memory — nothing here exists on disk. Reading files here queries live kernel and process data in real time. A powerful diagnostic tool for administrators.', examples: 'cpuinfo, meminfo, uptime, /proc/1234/ (per-process info)' },
      { name: 'root', desc: "The home directory for the root (superuser) account. Kept at the top level rather than inside /home so it's accessible even if /home is on a separate volume that fails to mount.", examples: "root's personal files, scripts, and admin configurations" },
      { name: 'run', desc: 'Runtime data for running processes — PID files, sockets, and lock files. Contents are cleared at each boot. Replaced the older /var/run on modern systems.', examples: 'sshd.pid, systemd/, dbus/system_bus_socket' },
      { name: 'sbin', desc: 'System administration binaries — commands typically run only by root. Contains tools for disk management, network configuration, and system maintenance that ordinary users do not need in daily operation.', examples: 'fdisk, iptables, fsck, reboot, ifconfig, useradd' },
      { name: 'srv', desc: 'Data served by this machine to the network. Web servers, FTP servers, and similar services store their publicly accessible content here by convention.', examples: '/srv/www/ (web content), /srv/ftp/' },
      { name: 'sys', desc: "A virtual filesystem (like /proc) that exposes the kernel's view of hardware devices and drivers. Used by device management tools — rarely interacted with directly by administrators.", examples: 'block/, bus/, class/, devices/ (kernel hardware model)' },
      { name: 'tmp', desc: 'Temporary files. Any process can create files here. Contents are wiped on every reboot. Never store anything important here — treat it as volatile scratch space.', examples: '(wiped on every reboot; use for short-lived scratch files only)' },
      {
        name: 'usr',
        desc: 'The second major hierarchy — contains the majority of user-space programs, libraries, and data. Most software installed via the package manager lands somewhere under /usr.',
        examples: '/usr/bin/, /usr/lib/, /usr/share/, /usr/local/',
        children: [
          { name: 'bin', desc: 'The majority of user commands installed on the system. While /bin contains only essentials needed at boot, /usr/bin contains thousands of programs installed via the package manager.', examples: 'python3, git, vim, curl, wget, ssh, grep, awk, tar' },
          { name: 'lib', desc: 'Shared libraries for programs in /usr/bin. The bulk of installed library files live here — far more than in the root-level /lib.', examples: 'libpython3.so, libssl.so, libcurl.so' },
          { name: 'local', desc: 'Software compiled or installed manually, outside the package manager. Keeping these files here prevents conflicts with package-managed software in /usr/bin.', examples: '/usr/local/bin/, /usr/local/lib/, /usr/local/share/' },
          { name: 'share', desc: 'Architecture-independent data shared among programs: documentation, manual pages, icons, locale data, and default configuration templates.', examples: 'man/ (manual pages), doc/, fonts/, locale/, applications/' },
        ]
      },
      {
        name: 'var',
        desc: 'Variable data — files that grow or change as the system runs. Logs, databases, mail queues, and print spools all live here. Often placed on its own filesystem partition to prevent runaway log growth from filling the root partition.',
        examples: '/var/log/, /var/www/, /var/lib/mysql/, /var/mail/',
        children: [
          { name: 'log', desc: 'System and application log files — the first place to look when troubleshooting. Logs are append-only text files that grow over time and are periodically rotated (archived) by logrotate.', examples: 'syslog, auth.log, kern.log, nginx/access.log, nginx/error.log' },
          { name: 'www', desc: 'The default document root for web servers (Apache, Nginx). HTML files, application code, and media served to web clients are typically stored here.', examples: '/var/www/html/index.html, /var/www/myapp/' },
          { name: 'lib', desc: 'Persistent application state data — database files, package manager metadata, and similar data that must survive reboots but is not configuration.', examples: 'mysql/ (database files), apt/ (package cache), dpkg/' },
        ]
      },
    ]
  };

  window.IDC.widgets['fs-tree'] = {
    render(container) {
      let activeLabel = null;

      function buildTree(node, depth, parentPath) {
        const isRoot = depth === 0;
        const fullPath = isRoot ? '/' : (parentPath === '/' ? '/' + node.name : parentPath + '/' + node.name);
        const hasChildren = !!(node.children && node.children.length);

        const wrap = document.createElement('div');
        wrap.className = 'fst-node';
        if (depth > 0) wrap.style.paddingLeft = (depth * 18) + 'px';

        const label = document.createElement('div');
        label.className = 'fst-label';

        const toggle = document.createElement('span');
        toggle.className = 'fst-toggle';
        toggle.textContent = hasChildren ? '▶' : ' ';

        const nameSpan = document.createElement('span');
        nameSpan.className = 'fst-name';
        nameSpan.textContent = isRoot ? '/' : node.name + '/';

        label.appendChild(toggle);
        label.appendChild(nameSpan);
        wrap.appendChild(label);

        let childWrap = null;
        if (hasChildren) {
          childWrap = document.createElement('div');
          childWrap.className = 'fst-children';
          childWrap.style.display = 'none';
          for (const child of node.children) {
            childWrap.appendChild(buildTree(child, depth + 1, fullPath));
          }
          wrap.appendChild(childWrap);
        }

        label.addEventListener('click', e => {
          e.stopPropagation();

          if (hasChildren) {
            const open = childWrap.style.display !== 'none';
            childWrap.style.display = open ? 'none' : 'block';
            toggle.textContent = open ? '▶' : '▼';
          }

          if (activeLabel) activeLabel.classList.remove('active');
          label.classList.add('active');
          activeLabel = label;

          showDetail(node, fullPath);
        });

        return wrap;
      }

      function showDetail(node, path) {
        const panel = container.querySelector('.fst-detail');
        panel.classList.remove('fst-detail-placeholder');
        panel.innerHTML = `
          <div class="fst-detail-path">${path}${path === '/' ? '' : '/'}</div>
          <div class="fst-detail-desc">${node.desc}</div>
          ${node.examples ? `
            <div class="fst-detail-section">Typical contents</div>
            <div class="fst-detail-examples">${node.examples}</div>
          ` : ''}`;
      }

      container.innerHTML = `
        <div class="fst-widget">
          <div class="fst-tree-panel"></div>
          <div class="fst-detail fst-detail-placeholder">
            <div class="fst-hint">← Click any directory to see what it contains</div>
          </div>
        </div>`;

      const treePanel = container.querySelector('.fst-tree-panel');
      const rootNode = buildTree(ROOT, 0, '');
      treePanel.appendChild(rootNode);

      // Auto-expand root on load
      const rootLabel  = treePanel.querySelector('.fst-label');
      const rootToggle = treePanel.querySelector('.fst-toggle');
      const rootKids   = treePanel.querySelector('.fst-children');
      if (rootKids) { rootKids.style.display = 'block'; rootToggle.textContent = '▼'; }
      if (rootLabel) { rootLabel.classList.add('active'); activeLabel = rootLabel; showDetail(ROOT, '/'); }
    }
  };
})();
